#!/bin/bash

# if averaging fits is wanted 
# python3 ramanavrgfits.py -d Median-subtracted -n 41 -m 10 -s S18_F70L_1_AX_01.txt

python3 ramanavrgspectra.py -d Median-subtracted -n 41 -m 10 -s S18_F70L_1_AX_01.txt